#product.version=2.0.20.1009
spring:
  application:
    name: science-analysis
  datasource:


server:
  port: 8115
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 102400
  servlet:
    context-path: /science-analysis

logging:
  level:
    com.hzsun.bigdata.metadata: debug
  file:
    name: logs/science-analysis.log

mybatis:
  mapper-locations: /mapper/*.xml
